name: "🐛 Bug report"
description: Report something that isn’t working as expected.
title: "[Bug]: "
labels: ["bug", "needs triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out all sections clearly to help us reproduce and fix the issue.

  - type: input
    id: version
    attributes:
      label: Library Version
      description: What version of the library are you using?
      placeholder: e.g. 1.2.3 or main branch
    validations:
      required: true

  - type: input
    id: environment
    attributes:
      label: Environment
      description: Node.js / npm / OS details
      placeholder: e.g. Node 20.5.1 / npm 10.5.0 / macOS 14.2
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened and what did you expect to happen?
      placeholder: |
        Describe the problem clearly, including expected vs. actual behavior.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: List precise steps or code to reproduce the issue.
      placeholder: |
        1. Install version X.Y.Z
        2. Run `npm start`
        3. See error message
      render: shell
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs or Stack Trace
      description: Paste any relevant output, error logs, or screenshots.
      render: shell
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues for duplicates.
          required: true
        - label: I have read the README and documentation.
          required: true

