name: "✨ Feature request"
description: Suggest an idea or improvement for this project.
title: "[Feature]: "
labels: ["enhancement", "needs triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a feature! Please describe clearly what you’d like to see and why.

  - type: input
    id: context
    attributes:
      label: Related Problem / Context
      description: Is your request related to a problem? Please describe.
      placeholder: e.g. It’s hard to integrate this with X, or performance is slow when Y.
    validations:
      required: false

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: What would you like to see added or changed?
      placeholder: |
        Explain how you’d like the feature to work, or include pseudo-code examples.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: List other approaches or explain why they don’t work well.
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add screenshots, links, or any other relevant context.
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues to make sure this feature hasn’t been requested already.
          required: true
        - label: I am willing to help implement this feature if guidance is provided.
          required: false

